-- info: USER 
INSERT INTO PINPAL.PUBLIC.USER(ID, NAME, EMAIL, PASSWORD, ABOUT, PBLC)
VALUES('GLOBAL~USER','USER','EMAIL','PASSWORD','ABOUT',1);

-- info: GUIDE 
-- ID: USER_ID + "~" + NAME
INSERT INTO PINPAL.PUBLIC.GUIDE(ID, USER_ID, NAME, ABOUT, PBLC, DEFAULT_ZOOM, DEFAULT_LAT, DEFAULT_LNG)
VALUES('GLOBAL~GUIDE','GLOBAL~USER','GUIDE','ABOUT',1,10,48.860357,2.336998);

-- info: ICON 
-- ID: PIN_COLL_ID + "~" + NAME
INSERT INTO PINPAL.PUBLIC.ICON(ID, PIN_COLL_ID, NAME, COLOR, STYLE)
VALUES('GLOBAL~ICON','GLOBAL~PIN_COLL','map-pin-simple','#c01f2c','regular');

-- info: PIN_COLL 
-- ID: GUIDE_ID + "~" + NAME
INSERT INTO PINPAL.PUBLIC.PIN_COLL(ID, USER_ID, GUIDE_ID, ICON_ID, NAME)
VALUES('GLOBAL~PIN_COLL','GLOBAL~USER','GLOBAL~GUIDE','GLOBAL~ICON','PIN_COLL');

-- info: PIN 
-- ID: PIN_COLL_ID + "~" + PLACE_ID
INSERT INTO PINPAL.PUBLIC.PIN(ID, PLACE_ID, PIN_COLL_ID, NAME, ABOUT, PHOTO)
VALUES('GLOBAL~PIN','PLACE_ID','GLOBAL~PIN_COLL','PIN','ABOUT','PHOTO');

-- info: PLACE_DETAILS  
-- ID: PLACE_ID (via Google Places API) 
INSERT INTO PINPAL.PUBLIC.PLACE_DETAILS(PLACE_ID, NAME, LAT, LNG, ADDRESS, COUNTRY, WEBSITE, PHONE, BUSINESS_STATUS, OPENING_HOURS, RATING, RATINGS_COUNT, SUMMARY, TYPES, PHOTOS)
VALUES('PLACE_ID','NAME',48.860357,2.336998,'ADDRESS','COUNTRY','WEBSITE','PHONE','BUSINESS_STATUS','OPENING_HOURS',1,1,'SUMMARY','TYPES','PHOTOS');