-- info: USER 
create or replace TABLE PINPAL.PUBLIC.USER (
	ID VARCHAR(24) NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	EMAIL VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	ABOUT VARCHAR(256),
	PBLC NUMBER(1,0) NOT NULL,
	unique (EMAIL),
	primary key (ID)
);

-- info: GUIDE 
-- ID: USER_ID + "~" + NAME
create or replace TABLE PINPAL.PUBLIC.GUIDE (
	ID VARCHAR(32) NOT NULL,
	USER_ID VARCHAR(24) NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	ABOUT VARCHAR(256),
	PBLC NUMBER(1,0) NOT NULL,
	DEFAULT_ZOOM NUMBER(2,0) NOT NULL,
	DEFAULT_LAT NUMBER(8,6) NOT NULL,
	DEFAULT_LNG NUMBER(9,6) NOT NULL,
	primary key (ID)
);

-- info: ICON 
-- ID: PIN_COLL_ID + "~" + NAME
create or replace TABLE PINPAL.PUBLIC.ICON (
	ID VARCHAR(98) NOT NULL,
	PIN_COLL_ID VARCHAR(65) NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	COLOR VARCHAR(7) NOT NULL,
	STYLE VARCHAR(7) NOT NULL,
	primary key (ID)
);

-- info: PIN_COLL 
-- ID: GUIDE_ID + "~" + NAME
create or replace TABLE PINPAL.PUBLIC.PIN_COLL (
	ID VARCHAR(65) NOT NULL,
	USER_ID VARCHAR(24) NOT NULL,
	GUIDE_ID VARCHAR(32) NOT NULL,
	ICON_ID VARCHAR(98) NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	primary key (ID)
);

-- info: PIN 
-- ID: PIN_COLL_ID + "~" + PLACE_ID
create or replace TABLE PINPAL.PUBLIC.PIN (
	ID VARCHAR(512) NOT NULL,
	PLACE_ID VARCHAR(512) NOT NULL,
	PIN_COLL_ID VARCHAR(65) NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	ABOUT VARCHAR(256),
	PHOTO VARCHAR(256),
	primary key (ID)
);

-- info: PLACE_DETAILS  
-- ID: PLACE_ID (via Google Places API) 
create or replace TABLE PINPAL.PUBLIC.PLACE_DETAILS (
	PLACE_ID VARCHAR(256) NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	LAT NUMBER(9,7) NOT NULL,
	LNG NUMBER(10,7) NOT NULL,
	ADDRESS VARCHAR(256),
	COUNTRY VARCHAR(56),
	WEBSITE VARCHAR(256),
	PHONE VARCHAR(24),
	BUSINESS_STATUS VARCHAR(24),
	OPENING_HOURS VARCHAR(256),
	RATING NUMBER(2,1),
	RATINGS_COUNT NUMBER(7,0),
	SUMMARY VARCHAR(150),
	TYPES VARCHAR(256),
	PHOTOS VARCHAR(256),
	primary key (PLACE_ID)
);


-- info: Synax for ID generation
-- Order of concatenation:
-- 1. User ID
-- 2. Guide ID
-- 3. Pin Collection ID